### ISSUE TITLE
Problems using it with #![no_std]

### ISSUE THREAD

**Issue by therealprof** [thejpster/rust-measurements#16]
I'm trying to optionally compile this crate as a dependency for my INA260 driver however, I'm somehow failing to get it compiled into one of my examples.

Basically I'm trying to get it into an example of my `stm32f042-hal` via the `ina260` crate. 
Inside the hal crates' `Cargo.toml` I have:
```
[dependencies.ina260]
default-features = false
features = ["measurements"]
```

Inside ina260's `Cargo.toml` I have:
```
[dependencies.measurements]
optional = true
version = "0.9.0"
```

However when I try to enable the measurements dependency and compile with `xargo` I get:
```
   Compiling libc v0.2.37
error[E0463]: can't find crate for `std`
  |
  = note: the `thumbv6m-none-eabi` target may not be installed

error: aborting due to previous error

If you want more information on this error, try using "rustc --explain E0463"
error: Could not compile `libc`.

To learn more, run the command again with --verbose.
```

I've no idea why it tries to go `std` here. Any idea how to address this?

`xargo tree` says:
```
...
├── ina260 v0.1.1 (file:///Users/egger/OSS/ina260)
│   [dependencies]
│   ├── cast v0.2.2 (*)
│   ├── embedded-hal v0.1.2 (*)
│   └── measurements v0.9.0
│       [dependencies]
│       └── time v0.1.39
│           [dependencies]
│           └── libc v0.2.37
│           [dev-dependencies]
│           └── winapi v0.3.4
...
```

**Comment by thejpster** [comment]
Oh damnit. I use the `time` crate because core didn't have a Duration, but
time uses libc, which needs a flag to make it no_std.

We could send a PR to the time crate, but they say they're in bugfix only
mode. Are there any other useful implementations of Duration we could use?

**Comment by thejpster** [comment]
Right. This time I've actually tested the `no_std` with xargo.

```
$ rustup run nightly xargo build --target=thumbv7em-none-eabi --features no_std
   Compiling measurements v0.10.0 (file:///home/jonathan/Documents/programming/rust-measurements)
    Finished dev [unoptimized + debuginfo] target(s) in 1.18 secs
```

It was troublingly non-trivial, due to a lack of float related functions, and having to swap std/core all over the place.

**Comment by thejpster** [comment]
Also to add, I suspect `no_std` only works on nightly because it needs the new `core::time` but that shouldn't be an issue.

**Comment by therealprof** [comment]
Thanks a lot. I can confirm that it works now. There's a distinct lack of fun using it on a MCU without FPU though as the binary size goes through the roof but that was sort of to be expected.
