### ISSUE TITLE
Crates.io links to outdated repo

### ISSUE THREAD

**Issue by JeftaDotEU** [thejpster/rust-measurements#18]
I don't know if the original author is still involved with this library, but his repository (https://github.com/jocull/rust-measurements) was last updated on October 3, 2017. The link on crates.io links to that URL, which means that people have to dig through fork graphs before they can see up-to-date code. Could you either make jocull update his version, or change the link on crates.io?

**Comment by thejpster** [comment]
Good point. @jocull which would you prefer - merge my changes or change the URL?

**Comment by jocull** [comment]
I swore that I had merged the changes. I believe you also have contributor access @thejpster. I'm not very plugged into the Rust community right now unfortunately, so it may be best if you update Crates.io with the latest. If it gets to be a big hassle we should update Crates.io to point at you for sure.

**Comment by jocull** [comment]
Started a pull for this -- looks like you already got the latest on Crates.io

**Comment by jocull** [comment]
Really, after more thought (whole minutes worth!) you should be the owner of this repo now @thejpster. Feel free to update Crates.io to point at you since you've put most of the work in 👍

**Comment by thejpster** [comment]
Much appreciated @jocull. It's still a team effort, but this will make the admin easier. Cheers.

**Comment by thejpster** [comment]
Done!
