### ISSUE TITLE
Add CHANGELOG

### ISSUE THREAD

**Issue by dbrgn** [thejpster/rust-measurements#20]
Since there is neither a changelog, nor clear version bump commits, nor tagged releases, it is quite hard to tell for example what happened between 0.9 and 0.10.

It would be great if you could add a changelog: See https://blog.dbrgn.ch/2015/12/1/rust-crates-keep-a-changelog/ and https://keepachangelog.com/.

**Comment by thejpster** [comment]
Releases back to 0.6.0 now tagged as Releases on Github. I hope this is useful. I'll create a CHANGELOG.md for the next release.

**Comment by dbrgn** [comment]
Thank you!
