### ISSUE TITLE
meter to feet, yard, furlong, mile could be slightly more accurate

### ISSUE THREAD

**Issue by tspiteri** [thejpster/rust-measurements#25]
Currently the constant expressions for `METER_TO_{INCH,FEET,YARD,FURLONG,MILE}` include `25.4`, which is not exactly representable, and thus the result is not the nearest representable float (`METER_TO_INCH` gets the good value by luck, but the others are slightly off).

```rust
// e.g. for mile this is the currently used expression
const METER_MILE_FACTOR: f64 = 1000.0 / (25.4 * 12.0 * 3.0 * 1760.0);
// while this yields a more accurate result
const BETTER_METER_MILE_FACTOR: f64 = 10000.0 / (254.0 * 12.0 * 3.0 * 1760.0);
// current 0.000621371192237334, better is 0.0006213711922373339
println!("current {}, better is {}", METER_MILE_FACTOR, BETTER_METER_MILE_FACTOR);
```

**Comment by tspiteri** [comment]
For the example above, writing the exact value represented by the `f64` yields:
  * 0.000,621,371,192,237,<b>334,026</b>,703,399,203,483,968,449,290,841,817,855,834,960,937,5 is the current value.
  * 0.000,621,371,192,237,<b>333,918</b>,283,181,954,933,525,048,545,561,730,861,663,818,359,375 is the better value.
  * 0.000,6(21,371,192,237,<b>333,969</b>,617,434,184,363,318,221,585,938,1) with the digits in brackets recurring is exact (as in actually exact, not exact `f64` representation).

**Comment by thejpster** [comment]
Good spot! Are you able to send through a PR?
