### ISSUE TITLE
Add 'Mass'

### ISSUE THREAD

**Issue by thejpster** [thejpster/rust-measurements#4]
Fundamental unit would be kg. Consider #2 as well for nice formatting in tons/stone/lbs/oz.

**Comment by lochsh** [comment]
I'm going to have a crack at this :)

**Comment by lochsh** [comment]
I think if you add me as a collaborator on the project, you will be able to assign me.

**Comment by thejpster** [comment]
I decided to rename weight to mass and add a new Force type. See my weight_and_mass branch.
